# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(limit):
    seq = [1,2]
    if limit <= seq[-1]:
        return seq

    lastNumber =  seq[len(seq) - 2] + seq[len(seq) - 1]
    while lastNumber <= limit:
        seq.append(lastNumber)
        lastNumber =  seq[len(seq) - 2] + seq[len(seq) - 1]
    return seq
        

if __name__ == "__main__":
    print(sum([x for x in fibonacci(4000000) if x % 2 == 0]))
    